layout_spectrum: 0.2529538
color:
  saturation: 0.8931257
  brandStrength: 0.7053038
  lightness: 0.840494
  rhythmicContrast: 0.6364124
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0
name: Litt Family
